repositories:
 - name: prometheus-community
   url: https://prometheus-community.github.io/helm-charts

releases:
- name: prometheus-stack
  namespace: monitoring
  chart: prometheus-community/kube-prometheus-stack
  wait: true
- name: grafana
  namespace: another
  chart: ../charts/grafana
  values:
  - "../../my-values/grafana/values.yaml"             # Values file (relative path to manifest)
  - ./values/{{ requiredEnv "PLATFORM_ENV" }}/config.yaml # Values file taken from path with environment variable. $PLATFORM_ENV must be set in the calling environment.
  wait: true