alertmanager:
  enabled: false
  
kubelet:
  serviceMonitor:
    interval: 5s
prometheus-node-exporter:
  prometheus:
    monitor:
      interval: 5s
      scrapeTimeout: 5s
  
prometheus:
  prometheusSpec:
    scrapeInterval: 5s
    scrapeTimeout: 5s
    additionalScrapeConfigs:
    - job_name: pushgateway
      honor_labels: true
      scrape_interval: 5s
      scrape_timeout: 5s
      static_configs:
      - targets: [prometheus-pushgateway:9091]