prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
    - job_name: pushgateway
      honor_labels: true
      static_configs:
      - targets: [prometheus-pushgateway:9091]
  scrapeInterval: 5s
  global:
    scrape_interval: 5s